### ISSUE TITLE
20211202 snapshot broken?

### ISSUE THREAD

**Issue by seaify** [binance-chain/bsc-snapshots#79]
after use the snapshot, why still need to sync data from 1year 2month ago?

and after run some time, get this error, 
```
panic: deletion not supported

goroutine 181219 [running]:
github.com/ethereum/go-ethereum/trie.(*StackTrie).TryUpdate(0xc038f2ae50, 0xc04d8b06a0, 0x20, 0x20, 0x282c678, 0x0, 0x0, 0x0, 0x0)
        github.com/ethereum/go-ethereum/trie/stacktrie.go:194 +0xd2
github.com/ethereum/go-ethereum/trie.VerifyRangeProof(0x2bec274a60f05240, 0x906c76eedf6e3071, 0x5acea042a9ac1783, 0xfbd4844540b5016a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/ethereum/go-ethereum/trie/proof.go:486 +0x1f2
github.com/ethereum/go-ethereum/eth/protocols/snap.(*Syncer).OnStorage(0xc
```

```
t=2021-12-06T02:37:03+0000 lvl=warn msg="Sanitizing cache to Go's GC limits" provided=32768 updated=21408
t=2021-12-06T02:37:03+0000 lvl=info msg="Set global gas cap"                 cap=25,000,000
t=2021-12-06T02:37:03+0000 lvl=info msg="Allocated trie memory caches"       clean="3.14 GiB" dirty="5.23 GiB"
t=2021-12-06T02:37:03+0000 lvl=info msg="Allocated cache and file handles"   database=/home/node/geth/chaindata cache="8.36 GiB" handles=524,288
t=2021-12-06T02:37:30+0000 lvl=info msg="Opened ancient database"            database=/home/node/geth/chaindata/ancient readonly=false
t=2021-12-06T02:37:30+0000 lvl=info msg="Initialised chain configuration"    config="{ChainID: 56 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0, Muir Glacier: 0, Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Berlin: <nil>, YOLO v3: <nil>, Engine: parlia}"
t=2021-12-06T02:37:31+0000 lvl=info msg="Initialising Ethereum protocol"     network=56 dbversion=8
t=2021-12-06T02:37:31+0000 lvl=info msg="Loaded most recent local header"    number=935,166 hash=0x221e3512a2a9be56ad4423420962dfffd975f24254cfeef5bfe6d7990f1a7811 td=1,870,190 age=1y2mo1w
t=2021-12-06T02:37:31+0000 lvl=info msg="Loaded most recent local full block" number=0       hash=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb665db62a2f3b02d2d57b5b td=1         age=1y7mo3w
t=2021-12-06T02:37:31+0000 lvl=info msg="Loaded most recent local fast block" number=924,234 hash=0x32dfbf8e5bfad64fa1a1fcacf3b0f1df9ae85f3da4240a6b167cb527fdb38355 td=1,848,326 age=1y2mo1w
t=2021-12-06T02:37:31+0000 lvl=info msg="Loaded last fast-sync pivot marker"  number=13,232,174
t=2021-12-06T02:37:31+0000 lvl=warn msg="Snapshot maintenance disabled (syncing)"
t=2021-12-06T02:37:31+0000 lvl=warn msg="Sanitizing invalid txpool reannounce time" provided=0s    updated=1m0s
t=2021-12-06T02:37:31+0000 lvl=info msg="Upgrading chain index"               type=bloombits percentage=3
```

**Comment by TehnobitSystems** [comment]
Not bad, this snapshot work fine.
